displayName=Racecar
author=KihiraLove
description=Transmogrifies Dom into the burrowed form of the Doom of Mokhaiotl
tags=doom,mokhaiotl,dom,transmog,car,racecar,pet
version=
plugins=com.racecar.Racecar
build=standard