displayName=Racecar
author=KihiraLove
description=Transmorgify your pet to the burrowed version of Doom
tags=doom,transmog,car,racecar,pet,transmogrify
version=
plugins=com.racecar.Racecar
build=standard