displayName=Racecar
author=KihiraLove
description=Adds a Metamorphosis option to Dom to change it to the burrowed phase of Doom. Requires a GPU renderer (GPU, 117 HD, GPU(Experimental), GPU (Legacy)
tags=doom,mokhaiotl,dom,pet,transmog,car,metamorph,metamorphosis
version=
plugins=com.racecar.Racecar
build=standard